### ISSUE TITLE
Source Of Detectors

### ISSUE THREAD

**Issue by think-in-universe** [ahnafalfariza/scavene#8]
Hey authors, you should mention that you have integrated the [detectors summarized by BlockSec](https://github.com/blocksecteam/rustle?tab=readme-ov-file#detectors) since you're using them [here](https://github.com/ahnafalfariza/scavene/blob/master/vulnerabilities/list_vulnerabilities.csv)

**Comment by ahnafalfariza** [comment]
Hi @think-in-universe, thank you

You’re right, I should clarify that we’ve integrated the detectors summarized by BlockSec. I’ll update the documentation shortly to properly mention it.

I initially added that repo as a submodule before https://github.com/ahnafalfariza/scavene/commit/0620b74498330cf52df90699ee506569398347f4, but I think I accidentally detached the submodule. 

Thank you anyway, will update it ASAP.
